spring:
  application:
    name: booktalk
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://3.36.235.110:3306/booktalk
    username: root
    password: ${MYSQL_SECRET}
  sql:
    init:
      mode: always

server:
  error:
    whitelabel:
      enabled: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
